#!/bin/sh
if (systemctl list-unit-files |grep smanager) then
  echo "Restarting smanager"
  /sbin/e-smith/signal-event manager2-refresh;
  systemctl restart smanager
else
 echo "Smanager not loaded"
fi
