#!/bin/sh
if (systemctl list-unit-files |grep smanager) then
  echo "Restarting smanager"
  /sbin/e-smith/signal-event smanager-refresh;
  systemctl restart smanager
else
 echo "smanager not loaded"
fi